#!/usr/bin/env python
"""
Turn the knowledge-base spreadsheet into the markdown the agent reads.

    python scripts/import_kb.py

WHY THERE IS A CONVERSION STEP AT ALL
-------------------------------------
The spreadsheet is the right place to EDIT the knowledge base — the office can
add a row without touching git, and the id / category / last_verified columns
make it reviewable as a document.

It is the wrong thing to read at runtime. It is a binary file, so a commit that
changes a rate shows up in git as "the file changed" and nothing more; nobody can
review what the agent is about to start telling customers. And a corrupt or
half-saved workbook would take the agent down at boot.

So the spreadsheet is the source, this script is the compiler, and the markdown
in knowledge/ is what ships. Editing the markdown by hand works but gets
overwritten on the next import — the header on each generated file says so.

Run it whenever the spreadsheet changes, then commit both.
"""

import re
import sys
from collections import OrderedDict
from pathlib import Path

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl is not installed. Run: uv pip install openpyxl")

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "knowledge" / "source"
OUT_DIR = ROOT / "knowledge"

REQUIRED = ("id", "category", "question", "answer")

#: Files in knowledge/ that this script owns and may overwrite. Anything else
#: there is hand-written and is left alone.
GENERATED_MARK = "<!-- generated by scripts/import_kb.py -->"


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-") or "misc"


def read_rows(path: Path) -> list[dict]:
    workbook = openpyxl.load_workbook(path, data_only=True)
    sheet = workbook[workbook.sheetnames[0]]
    rows = list(sheet.iter_rows(values_only=True))
    if not rows:
        sys.exit(f"{path.name} is empty.")

    header = [str(c).strip().lower() if c else "" for c in rows[0]]
    missing = [c for c in REQUIRED if c not in header]
    if missing:
        sys.exit(f"{path.name} is missing column(s): {', '.join(missing)}")

    out = []
    for row in rows[1:]:
        record = {key: ("" if value is None else str(value).strip())
                  for key, value in zip(header, row)}
        if record.get("id") and record.get("question") and record.get("answer"):
            out.append(record)
    return out


def render(category: str, records: list[dict], source_name: str) -> str:
    lines = [
        GENERATED_MARK,
        f"<!-- source: knowledge/source/{source_name} — edit there, then re-run "
        "scripts/import_kb.py -->",
        "",
        f"# {category}",
        "",
    ]
    for record in records:
        lines.append(f"## {record['question']}")
        lines.append("")
        lines.append(record["answer"])
        if note := record.get("notes"):
            # Kept, not discarded. These are how the office wants a topic
            # handled — "ask how many movers before quoting", "escalate the
            # exact amount" — which is real operating knowledge that exists
            # nowhere else. schemas/persona.py explains the marker to the model.
            lines.append("")
            lines.append(f"HANDLING: {note}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    sources = sorted(SOURCE_DIR.glob("*.xlsx"))
    if not sources:
        sys.exit(f"No .xlsx found in {SOURCE_DIR}")

    records: list[dict] = []
    source_name = sources[0].name
    for path in sources:
        records.extend(read_rows(path))

    if not records:
        sys.exit("No usable rows found.")

    # Duplicate ids mean two rows are fighting over the same fact, and the agent
    # would cheerfully state both. Worth stopping for.
    seen: dict[str, str] = {}
    for record in records:
        if record["id"] in seen:
            sys.exit(f"Duplicate id {record['id']!r} — ids must be unique.")
        seen[record["id"]] = record["question"]

    grouped: OrderedDict[str, list[dict]] = OrderedDict()
    for record in records:
        grouped.setdefault(record["category"] or "General", []).append(record)

    # Clear out previously generated files, so a category renamed in the
    # spreadsheet does not leave the old file behind for the agent to keep
    # answering from.
    for existing in OUT_DIR.glob("*.md"):
        text = existing.read_text(encoding="utf-8")
        if text.startswith(GENERATED_MARK):
            existing.unlink()

    print(f"{len(records)} entries from {source_name}\n")
    for category, entries in grouped.items():
        path = OUT_DIR / f"{slug(category)}.md"
        path.write_text(render(category, entries, source_name), encoding="utf-8")
        print(f"  {path.name:<16} {len(entries):>3} entries")

    flagged = [r for r in records if re.search(r"\bconfirm\b", r.get("notes", ""), re.I)]
    if flagged:
        print("\n  Needs a decision before this is live:")
        for record in flagged:
            print(f"    {record['id']}  {record['question']}")
            print(f"        {record['notes']}")


if __name__ == "__main__":
    main()
